services:
  aso-shop-postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asosa_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./.env:/app/.env
    ports:
      - '8000:8000'
    depends_on:
      aso-shop-postgres:
        condition: service_healthy
    command: >
      sh -c "pnpm install && pnpm build && pnpm start"

volumes:
  postgres_data:
    name: postgres_data
